name = "biswaas"
compatibility_date = "2026-04-01"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = ["nodejs_compat"]

[vars]
CONVEX_URL = "https://outgoing-warbler-836.convex.site"
PUBLIC_CONVEX_URL = "https://outgoing-warbler-836.convex.cloud"
PUBLIC_CONVEX_SITE_URL = "https://outgoing-warbler-836.convex.site"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
