name = "biswaas-api-proxy"
main = "src/index.ts"
compatibility_date = "2026-04-01"

[vars]
CONVEX_URL = "https://outgoing-warbler-836.convex.site"

[[routes]]
pattern = "api.biswaas.np/v1/*"
zone_name = "biswaas.np"
